# Конфигурация платёжных систем
YOOKASSA_SHOP_ID = "YOUR_SHOP_ID"
YOOKASSA_SECRET_KEY = "YOUR_SECRET_KEY"

CLOUDPAYMENTS_PUBLIC_ID = "YOUR_PUBLIC_ID"
CLOUDPAYMENTS_SECRET_KEY = "YOUR_SECRET_KEY"

TELEGRAM_BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"
